//! The binding table: which keys, in which mode, mean which [`Action`].
//!
//! ```text
//! KeyEvent  →  KeyChord  →  KeySeq  →  (Mode, KeySeq)  →  Action
//!           normalize    one or two    the table         what to do
//! ```
//!
//! # Why a table and not a `match`
//!
//! Decision D8: the keys match the rmpc muscle memory the user already has, and
//! they are remappable without recompiling. A `match` on `KeyCode` can do the
//! first and not the second, and it also cannot be *read* — and the help overlay
//! (task 26) is generated by reading this table, which is what makes it impossible
//! for the help to document a binding the user has remapped away.
//!
//! # Modes
//!
//! A key means different things depending on what is on screen, and the same
//! `ctrl-u` is "half a page up" in the browser and "clear the line" in the command
//! line. [`Mode`] is the discriminator, so the table is keyed by `(Mode, KeySeq)`
//! and each mode is configured by its own section of `keys.toml`.
//!
//! Only [`Mode::Browser`], [`Mode::TagEdit`] and [`Mode::Command`] can be reached
//! today; the views that put the app into the other two arrive with tasks 24 and
//! 25. Their default bindings are here and tested anyway, because what those tasks
//! need from this one is a table they can bind into rather than one to invent.
//!
//! # Normalization, and the `shift` problem
//!
//! Terminals disagree about `shift`. A capital `J` arrives as `Char('J')` from one
//! terminal and as `Char('j')` with [`KeyModifiers::SHIFT`] from another, and the
//! Kitty protocol adds a third spelling with modifiers nobody asked about.
//! [`KeyChord::new`] folds all of that into one shape:
//!
//! - **`shift` is never part of a chord whose key is a character.** It is folded
//!   into the character's case, so `"J"`, `"shift-j"` and `Char('j')+SHIFT` are all
//!   the same chord. This is also why `?`, `:` and `/` match on every terminal:
//!   `'?'.to_uppercase()` is `'?'`, so the modifier simply disappears;
//! - **`shift-tab` is `backtab`**, which is what crossterm reports;
//! - **modifiers that cannot be bound are dropped**, so a terminal that reports
//!   `KEYPAD` on the arrow keys does not stop `down` from matching.
//!
//! That turns the task's pitfall — "terminals report `ctrl-shift-x` inconsistently"
//! — into one chord rather than three, and the defaults still avoid `ctrl-shift`
//! entirely.
//!
//! # Two-key sequences
//!
//! `gg` is two presses with a short deadline between them, and the state that makes
//! that work lives in [`Keys`] rather than in [`KeyMap`]: the table is a pure
//! function of the configuration, and the half-finished sequence is a property of
//! the session. A lone `g` that is not followed by anything in
//! [`SEQUENCE_TIMEOUT`] does nothing at all.
//!
//! A complete binding always wins over a prefix: if a config binds `g` on its own,
//! `g` fires immediately and `gg` can never be reached — which is a
//! [`KeyWarning::Unreachable`] at startup rather than a silent surprise.

use std::collections::HashMap;
use std::fmt::Write as _;
use std::time::{Duration, Instant};

use camino::{Utf8Path, Utf8PathBuf};
use crossterm::event::{KeyCode, KeyEvent, KeyModifiers};

use super::action::Action;

/// How long the second key of a sequence has to arrive.
///
/// Long enough for `gg` typed by a human, short enough that a lone `g` does not
/// leave the app feeling stuck. Vim's own default is a second; this is shorter
/// because there is exactly one sequence and no ambiguity to wait out.
pub const SEQUENCE_TIMEOUT: Duration = Duration::from_millis(600);

/// The modifiers a binding may name. Anything else a terminal reports is dropped.
const BINDABLE: KeyModifiers = KeyModifiers::CONTROL
    .union(KeyModifiers::ALT)
    .union(KeyModifiers::SHIFT);

/// The action name that removes a binding instead of adding one.
const UNBIND: &str = "none";

// ---------------------------------------------------------------------------
// Modes
// ---------------------------------------------------------------------------

/// Which set of bindings is in force.
///
/// The name is also the `keys.toml` section header, which is why there is only one
/// spelling of each.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Mode {
    /// The library browser, and the base of the view stack.
    Browser,
    /// The tag editor (task 23). A form, so letters type rather than command.
    TagEdit,
    /// The staged-operations view (task 24).
    Pending,
    /// The incremental search line (task 25).
    Search,
    /// The `:` command line.
    Command,
}

impl Mode {
    /// Every mode, in the order the help overlay lists them.
    pub const ALL: &'static [Self] = &[
        Self::Browser,
        Self::Pending,
        Self::TagEdit,
        Self::Search,
        Self::Command,
    ];

    /// The `keys.toml` section header for this mode.
    #[must_use]
    pub fn name(self) -> &'static str {
        match self {
            Self::Browser => "browser",
            Self::TagEdit => "tagedit",
            Self::Pending => "pending",
            Self::Search => "search",
            Self::Command => "command",
        }
    }

    /// The mode a `keys.toml` section header names.
    #[must_use]
    pub fn from_name(name: &str) -> Option<Self> {
        Self::ALL.iter().copied().find(|mode| mode.name() == name)
    }
}

impl std::fmt::Display for Mode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.name())
    }
}

// ---------------------------------------------------------------------------
// One key
// ---------------------------------------------------------------------------

/// One keypress, normalized so that every terminal's spelling of it is the same.
///
/// See the [module documentation][self] for what normalization does and why it has
/// to happen before anything is looked up.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct KeyChord {
    code: KeyCode,
    mods: KeyModifiers,
}

impl KeyChord {
    /// A chord from a key and its modifiers, normalized.
    #[must_use]
    pub fn new(code: KeyCode, mods: KeyModifiers) -> Self {
        let mut mods = mods & BINDABLE;
        let mut code = code;

        match code {
            KeyCode::Char(c) => {
                // `shift` lives in the character's case and nowhere else, so the
                // three ways a terminal can report a capital become one chord.
                if mods.contains(KeyModifiers::SHIFT)
                    && let Some(upper) = single_uppercase(c)
                {
                    code = KeyCode::Char(upper);
                }
                mods.remove(KeyModifiers::SHIFT);
            }
            // What `shift-tab` actually arrives as.
            KeyCode::Tab if mods.contains(KeyModifiers::SHIFT) => {
                code = KeyCode::BackTab;
                mods.remove(KeyModifiers::SHIFT);
            }
            KeyCode::BackTab => mods.remove(KeyModifiers::SHIFT),
            _ => {}
        }

        Self { code, mods }
    }

    /// The chord a terminal event is.
    #[must_use]
    pub fn from_event(key: KeyEvent) -> Self {
        Self::new(key.code, key.modifiers)
    }

    /// An unmodified character key.
    #[must_use]
    pub fn plain(c: char) -> Self {
        Self::new(KeyCode::Char(c), KeyModifiers::NONE)
    }

    /// The chord `spec` names, in `keys.toml` notation: `j`, `G`, `ctrl-d`,
    /// `space`, `enter`, `f1`.
    ///
    /// # Errors
    ///
    /// [`KeyError::UnknownKey`] for a name that is not a single character and not
    /// in the table of named keys, and [`KeyError::Empty`] for nothing at all.
    pub fn parse(spec: &str) -> Result<Self, KeyError> {
        let mut rest = spec;
        let mut mods = KeyModifiers::NONE;

        // Peel modifier prefixes. `-` is itself a binding, so a prefix is only a
        // prefix when the text before the dash spells a modifier out in full:
        // abbreviating would make `a-b` ambiguous between alt-b and two keys.
        while let Some(dash) = rest.find('-') {
            let (head, tail) = rest.split_at(dash);
            let modifier = match head.to_ascii_lowercase().as_str() {
                "ctrl" | "control" => KeyModifiers::CONTROL,
                "alt" | "meta" => KeyModifiers::ALT,
                "shift" => KeyModifiers::SHIFT,
                _ => break,
            };
            mods |= modifier;
            rest = &tail[1..];
        }

        Ok(Self::new(parse_code(rest)?, mods))
    }

    /// Whether this chord is a character that should be typed rather than obeyed.
    ///
    /// The command line inserts anything unbound that answers yes, which is how
    /// `:move x` types six letters without six bindings.
    #[must_use]
    pub fn typed(self) -> Option<char> {
        match self.code {
            // A modifier means it was a command that nothing claimed, not text.
            // `alt` included: `alt-j` is not a `j`.
            KeyCode::Char(c) if self.mods.is_empty() && !c.is_control() => Some(c),
            _ => None,
        }
    }
}

impl std::fmt::Display for KeyChord {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        if self.mods.contains(KeyModifiers::CONTROL) {
            f.write_str("ctrl-")?;
        }
        if self.mods.contains(KeyModifiers::ALT) {
            f.write_str("alt-")?;
        }
        // Only ever set on a key with no case to fold it into.
        if self.mods.contains(KeyModifiers::SHIFT) {
            f.write_str("shift-")?;
        }
        match self.code {
            KeyCode::Char(' ') => f.write_str("space"),
            KeyCode::Char(c) => f.write_char(c),
            KeyCode::Enter => f.write_str("enter"),
            KeyCode::Esc => f.write_str("esc"),
            KeyCode::Tab => f.write_str("tab"),
            KeyCode::BackTab => f.write_str("shift-tab"),
            KeyCode::Backspace => f.write_str("backspace"),
            KeyCode::Delete => f.write_str("delete"),
            KeyCode::Insert => f.write_str("insert"),
            KeyCode::Home => f.write_str("home"),
            KeyCode::End => f.write_str("end"),
            KeyCode::PageUp => f.write_str("pageup"),
            KeyCode::PageDown => f.write_str("pagedown"),
            KeyCode::Up => f.write_str("up"),
            KeyCode::Down => f.write_str("down"),
            KeyCode::Left => f.write_str("left"),
            KeyCode::Right => f.write_str("right"),
            KeyCode::F(n) => write!(f, "f{n}"),
            // Unreachable from `parse`, so nothing in the table displays this; a
            // terminal can still send one, and a chord that cannot be written is
            // a chord that cannot be bound.
            other => write!(f, "<{other:?}>"),
        }
    }
}

/// The key a name refers to. A single character is itself; everything else is
/// spelled out.
fn parse_code(name: &str) -> Result<KeyCode, KeyError> {
    // The single-character case first, so `f` is the letter and `f1` is the
    // function key.
    let mut chars = name.chars();
    if let (Some(c), None) = (chars.next(), chars.next()) {
        return Ok(KeyCode::Char(c));
    }

    let code = match name.to_ascii_lowercase().as_str() {
        "" => return Err(KeyError::Empty),
        "enter" | "return" | "cr" => KeyCode::Enter,
        "esc" | "escape" => KeyCode::Esc,
        "tab" => KeyCode::Tab,
        "backtab" => KeyCode::BackTab,
        "space" => KeyCode::Char(' '),
        "backspace" | "bs" => KeyCode::Backspace,
        "delete" | "del" => KeyCode::Delete,
        "insert" | "ins" => KeyCode::Insert,
        "home" => KeyCode::Home,
        "end" => KeyCode::End,
        "pageup" | "pgup" => KeyCode::PageUp,
        "pagedown" | "pgdn" => KeyCode::PageDown,
        "up" => KeyCode::Up,
        "down" => KeyCode::Down,
        "left" => KeyCode::Left,
        "right" => KeyCode::Right,
        other => match other
            .strip_prefix('f')
            .and_then(|digits| digits.parse::<u8>().ok())
        {
            Some(n) if (1..=12).contains(&n) => KeyCode::F(n),
            _ => return Err(KeyError::UnknownKey(name.to_owned())),
        },
    };
    Ok(code)
}

/// `c` uppercased, when that is one character.
///
/// `ß` uppercases to `SS`, which is not a key; a chord that cannot be written as
/// one character keeps the case it arrived in.
fn single_uppercase(c: char) -> Option<char> {
    let mut upper = c.to_uppercase();
    match (upper.next(), upper.next()) {
        (Some(one), None) => Some(one),
        _ => None,
    }
}

// ---------------------------------------------------------------------------
// One or two keys
// ---------------------------------------------------------------------------

/// What the user pressed: one chord, or two in a row.
///
/// Two is the limit the task sets, and a fixed shape rather than a `Vec` says so
/// in the type: there is no `ggg`, and nothing has to handle one.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct KeySeq {
    first: KeyChord,
    second: Option<KeyChord>,
}

impl KeySeq {
    /// A single keypress.
    #[must_use]
    pub fn single(chord: KeyChord) -> Self {
        Self {
            first: chord,
            second: None,
        }
    }

    /// Two keypresses in a row.
    #[must_use]
    pub fn pair(first: KeyChord, second: KeyChord) -> Self {
        Self {
            first,
            second: Some(second),
        }
    }

    /// The sequence `spec` names.
    ///
    /// Three spellings, all of which appear in `docs/keys.example.toml`:
    ///
    /// - `"j"`, `"ctrl-d"` — one chord;
    /// - `"gg"` — two plain characters written together, the way vim writes it;
    /// - `"g g"`, `"ctrl-x s"` — two chords separated by a space, which is the only
    ///   way to write a sequence involving a modifier or a named key.
    ///
    /// # Errors
    ///
    /// [`KeyError::Empty`] for nothing, [`KeyError::TooLong`] for more than two
    /// chords, and [`KeyError::UnknownKey`] for a chord that cannot be parsed.
    pub fn parse(spec: &str) -> Result<Self, KeyError> {
        let parts: Vec<&str> = spec.split_whitespace().collect();
        match parts.as_slice() {
            [] => Err(KeyError::Empty),
            [one] => {
                if let Ok(chord) = KeyChord::parse(one) {
                    return Ok(Self::single(chord));
                }
                // Not a chord. Two bare characters is the vim spelling of a
                // sequence; anything else is a name nobody knows.
                let chars: Vec<char> = one.chars().collect();
                match chars.as_slice() {
                    [a, b] => Ok(Self::pair(KeyChord::plain(*a), KeyChord::plain(*b))),
                    _ => Err(KeyError::UnknownKey((*one).to_owned())),
                }
            }
            [a, b] => Ok(Self::pair(KeyChord::parse(a)?, KeyChord::parse(b)?)),
            _ => Err(KeyError::TooLong(spec.trim().to_owned())),
        }
    }

    /// The first chord, which is also what makes this sequence a prefix.
    #[must_use]
    pub fn first(&self) -> KeyChord {
        self.first
    }

    /// Whether this is two keys rather than one.
    #[must_use]
    pub fn is_pair(&self) -> bool {
        self.second.is_some()
    }
}

impl std::fmt::Display for KeySeq {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let Some(second) = self.second else {
            return write!(f, "{}", self.first);
        };
        // `gg`, not `g g` — but `ctrl-x s`, because `ctrl-xs` is not a thing.
        let joined = self.first.typed().is_some() && second.typed().is_some();
        if joined {
            write!(f, "{}{second}", self.first)
        } else {
            write!(f, "{} {second}", self.first)
        }
    }
}

/// Why a key specification could not be read.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum KeyError {
    /// An empty string, or a section key with nothing in it.
    #[error("no key named")]
    Empty,
    /// A name that is neither one character nor a key this program knows.
    #[error("no key called `{0}`")]
    UnknownKey(String),
    /// Three or more chords. Two is the limit.
    #[error("`{0}` is more than two keys; a sequence is one or two")]
    TooLong(String),
}

// ---------------------------------------------------------------------------
// The table
// ---------------------------------------------------------------------------

/// Which keys mean which actions, in which mode.
///
/// A pure function of the defaults and the configuration: nothing in here knows
/// what is on screen or what was pressed a moment ago. That is [`Keys`]'s job, and
/// the split is what lets the help overlay be generated from a value a test can
/// build in one line.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct KeyMap {
    bindings: HashMap<(Mode, KeySeq), Action>,
}

impl KeyMap {
    /// An empty table, which binds nothing at all.
    #[must_use]
    pub fn empty() -> Self {
        Self {
            bindings: HashMap::new(),
        }
    }

    /// The bindings from `docs/tasks/21-keymap.md`.
    ///
    /// Spelled in `keys.toml` notation rather than built out of [`KeyCode`]s, so
    /// that the defaults exercise the same parser the user's file goes through: a
    /// spelling that works here is a spelling that works there.
    ///
    /// # Panics
    ///
    /// If one of the spellings below is not parseable, which is a bug in this
    /// function and is caught by its own test.
    #[must_use]
    pub fn defaults() -> Self {
        let mut map = Self::empty();
        for (mode, table) in DEFAULTS {
            for (spec, action) in *table {
                let seq = KeySeq::parse(spec)
                    .unwrap_or_else(|err| panic!("default binding `{spec}` does not parse: {err}"));
                map.bind(*mode, seq, *action);
            }
        }
        map
    }

    /// Bind `seq` in `mode`, replacing whatever was there.
    ///
    /// Replacing and not adding: a table from a sequence to one action is what
    /// makes "rebinding a key does not leave the old binding active" true by
    /// construction rather than by remembering to remove things.
    pub fn bind(&mut self, mode: Mode, seq: KeySeq, action: Action) {
        self.bindings.insert((mode, seq), action);
    }

    /// Remove a binding, which is what `"R" = "none"` does.
    ///
    /// Returns what was there.
    pub fn unbind(&mut self, mode: Mode, seq: KeySeq) -> Option<Action> {
        self.bindings.remove(&(mode, seq))
    }

    /// What `seq` does in `mode`, if anything.
    #[must_use]
    pub fn action(&self, mode: Mode, seq: KeySeq) -> Option<Action> {
        self.bindings.get(&(mode, seq)).copied()
    }

    /// Whether `chord` starts a two-key sequence that is still reachable.
    ///
    /// "Still reachable" is the important half: a chord that is bound on its own
    /// fires immediately, so it is not a prefix even when a longer sequence starts
    /// with it. That ambiguity is reported by [`KeyMap::unreachable`] at load time.
    #[must_use]
    pub fn is_prefix(&self, mode: Mode, chord: KeyChord) -> bool {
        if self.action(mode, KeySeq::single(chord)).is_some() {
            return false;
        }
        self.bindings
            .keys()
            .any(|(m, seq)| *m == mode && seq.is_pair() && seq.first() == chord)
    }

    /// Every sequence bound in `mode`, with what it does.
    #[must_use]
    pub fn bindings(&self, mode: Mode) -> Vec<(KeySeq, Action)> {
        self.bindings
            .iter()
            .filter(|((m, _), _)| *m == mode)
            .map(|((_, seq), action)| (*seq, *action))
            .collect()
    }

    /// The shortest key bound to `action` in `mode`, if any is.
    ///
    /// For a hint that names the key the user actually has: `? help` when `?` is
    /// bound to it, `f1 help` when that is what they chose, and nothing at all when
    /// they have unbound it.
    #[must_use]
    pub fn key_for(&self, mode: Mode, action: Action) -> Option<String> {
        self.bindings(mode)
            .into_iter()
            .filter(|(_, bound)| *bound == action)
            .map(|(seq, _)| seq.to_string())
            .min_by(|a, b| {
                a.chars()
                    .count()
                    .cmp(&b.chars().count())
                    .then_with(|| a.cmp(b))
            })
    }

    /// The sequences that can never fire because their first chord is bound on its
    /// own, as `(mode, shadowed, shadowing action)`.
    ///
    /// The defaults produce none of these. A configuration that binds `g` makes
    /// `gg` unreachable, and saying so at startup is the difference between a
    /// surprising keymap and an explained one.
    #[must_use]
    pub fn unreachable(&self) -> Vec<(Mode, KeySeq, Action)> {
        let mut found: Vec<(Mode, KeySeq, Action)> = self
            .bindings
            .keys()
            .filter(|(_, seq)| seq.is_pair())
            .filter_map(|(mode, seq)| {
                let shadow = self.action(*mode, KeySeq::single(seq.first()))?;
                Some((*mode, *seq, shadow))
            })
            .collect();
        // A `HashMap` has no order and a warning list is read by a human.
        found.sort_by_key(|(mode, seq, _)| (mode.name(), seq.to_string()));
        found
    }

    /// The help overlay's content, derived from this table.
    ///
    /// One section per mode, and within a section one row per action in
    /// [`Action::ALL`] order — which is grouped the way the task's own table is,
    /// rather than alphabetically by key. Every key bound to the action is listed,
    /// so `j / down` is one row and not two.
    ///
    /// Generated and not written down, which is the point: a remapped key changes
    /// this, and a help page cannot document a binding that is not here.
    #[must_use]
    pub fn help(&self) -> Vec<HelpSection> {
        Mode::ALL
            .iter()
            .map(|&mode| {
                let bound = self.bindings(mode);
                let rows = Action::ALL
                    .iter()
                    .filter_map(|&action| {
                        let mut keys: Vec<String> = bound
                            .iter()
                            .filter(|(_, bound_action)| *bound_action == action)
                            .map(|(seq, _)| seq.to_string())
                            .collect();
                        if keys.is_empty() {
                            return None;
                        }
                        // Shortest first, so `j / down` reads the way the task's
                        // table does and the column stays narrow.
                        keys.sort_by(|a, b| {
                            a.chars().count().cmp(&b.chars().count()).then(a.cmp(b))
                        });
                        Some(HelpRow {
                            keys: keys.join(" / "),
                            action,
                        })
                    })
                    .collect();
                HelpSection { mode, rows }
            })
            .collect()
    }
}

impl Default for KeyMap {
    fn default() -> Self {
        Self::defaults()
    }
}

/// One mode's worth of help.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HelpSection {
    /// The mode these bindings apply in.
    pub mode: Mode,
    /// One row per action that has a key, in [`Action::ALL`] order.
    pub rows: Vec<HelpRow>,
}

/// One line of help: the keys, and what they do.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HelpRow {
    /// Every key bound to the action, e.g. `j / down`.
    pub keys: String,
    /// What they do. The text comes from [`Action::help`].
    pub action: Action,
}

/// The default bindings, by mode.
///
/// `ctrl-u` appearing twice with two meanings is the clearest argument for modes
/// there is: half a page up where there is a page, and clear-the-line where there
/// is a line.
const DEFAULTS: &[(Mode, &[(&str, Action)])] = &[
    (
        Mode::Browser,
        &[
            ("h", Action::Left),
            ("left", Action::Left),
            ("j", Action::Down),
            ("down", Action::Down),
            ("k", Action::Up),
            ("up", Action::Up),
            ("l", Action::Right),
            ("right", Action::Right),
            ("gg", Action::Top),
            ("G", Action::Bottom),
            ("ctrl-d", Action::HalfPageDown),
            ("ctrl-u", Action::HalfPageUp),
            ("enter", Action::Open),
            ("-", Action::Parent),
            ("backspace", Action::Parent),
            ("tab", Action::SwitchPane),
            ("space", Action::ToggleMark),
            ("v", Action::VisualSelect),
            ("a", Action::MarkAll),
            ("A", Action::UnmarkAll),
            ("e", Action::EditTags),
            ("m", Action::StageMove),
            ("r", Action::Rename),
            ("d", Action::StageDelete),
            ("o", Action::Organize),
            ("p", Action::ShowPending),
            ("c", Action::Commit),
            ("x", Action::DiscardPending),
            ("u", Action::Undo),
            ("/", Action::Search),
            ("n", Action::SearchNext),
            ("N", Action::SearchPrev),
            ("f", Action::Filter),
            ("F", Action::FindLibrary),
            ("esc", Action::Cancel),
            (":", Action::CommandMode),
            ("?", Action::Help),
            ("R", Action::Rescan),
            ("q", Action::Quit),
        ],
    ),
    (
        // Task 24. `dd` unstages here rather than `d` staging a delete, which is
        // the one verb that means something different in this view than in the
        // browser — and it is the doubled key for the same reason vim's is:
        // taking a line out of a list is worth two deliberate keystrokes when
        // the list is what is about to happen to somebody's library.
        Mode::Pending,
        &[
            ("j", Action::Down),
            ("down", Action::Down),
            ("k", Action::Up),
            ("up", Action::Up),
            ("gg", Action::Top),
            ("G", Action::Bottom),
            ("ctrl-d", Action::HalfPageDown),
            ("ctrl-u", Action::HalfPageUp),
            // Unfolding a playlist's diff, or a refused operation's reasons.
            ("enter", Action::Open),
            ("space", Action::Open),
            ("l", Action::Right),
            ("right", Action::Right),
            ("h", Action::Left),
            ("left", Action::Left),
            ("dd", Action::Unstage),
            ("c", Action::Commit),
            ("x", Action::DiscardPending),
            ("u", Action::Undo),
            ("p", Action::ShowPending),
            ("esc", Action::Cancel),
            (":", Action::CommandMode),
            ("?", Action::Help),
            ("q", Action::Quit),
        ],
    ),
    (
        // Task 23. The one mode with two states in it: moving between the form's
        // fields, where a bare letter is a verb, and typing into one of them,
        // where it is a letter. Only the text-editing actions are in force while a
        // field is open — see `App::on_key` — so `j` moves between fields and
        // still types a `j` into one, without a second mode for a user to
        // configure.
        Mode::TagEdit,
        &[
            ("j", Action::Down),
            ("down", Action::Down),
            ("k", Action::Up),
            ("up", Action::Up),
            ("gg", Action::Top),
            ("G", Action::Bottom),
            ("tab", Action::Down),
            ("backtab", Action::Up),
            ("left", Action::Left),
            ("right", Action::Right),
            ("i", Action::EditField),
            ("enter", Action::Submit),
            ("C", Action::ClearField),
            ("T", Action::TitleFromFilename),
            ("N", Action::RenumberTracks),
            ("w", Action::StageTags),
            ("W", Action::StageAndCommit),
            ("backspace", Action::DeleteChar),
            ("ctrl-u", Action::ClearLine),
            ("esc", Action::Cancel),
            ("?", Action::Help),
        ],
    ),
    (
        // Task 25. `ctrl-n` / `ctrl-p` cycle matches while the pattern is still
        // being typed, which `n` / `N` cannot do in a line of text.
        Mode::Search,
        &[
            ("left", Action::Left),
            ("right", Action::Right),
            ("ctrl-n", Action::SearchNext),
            ("ctrl-p", Action::SearchPrev),
            ("enter", Action::Submit),
            ("backspace", Action::DeleteChar),
            ("ctrl-u", Action::ClearLine),
            ("esc", Action::Cancel),
        ],
    ),
    (
        Mode::Command,
        &[
            ("left", Action::Left),
            ("right", Action::Right),
            ("enter", Action::Submit),
            ("backspace", Action::DeleteChar),
            ("ctrl-u", Action::ClearLine),
            ("esc", Action::Cancel),
        ],
    ),
];

// ---------------------------------------------------------------------------
// The session's half-finished sequence
// ---------------------------------------------------------------------------

/// The table plus the one piece of state a keymap needs: the first half of `gg`.
#[derive(Debug, Clone)]
pub struct Keys {
    map: KeyMap,
    partial: Option<Partial>,
}

/// A chord that might be the start of a sequence, and when it was pressed.
#[derive(Debug, Clone, Copy)]
struct Partial {
    chord: KeyChord,
    at: Instant,
}

/// What a keypress turned out to mean.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Resolution {
    /// Do this.
    Act(Action),
    /// This might be the first half of a sequence; the next key decides.
    Partial,
    /// Nothing is bound to it. The view may still want it as text.
    Nothing,
}

impl Keys {
    /// A session's keys, over this table.
    #[must_use]
    pub fn new(map: KeyMap) -> Self {
        Self { map, partial: None }
    }

    /// The table, for the help overlay.
    #[must_use]
    pub fn map(&self) -> &KeyMap {
        &self.map
    }

    /// What `key` means in `mode`, given what was pressed before it.
    ///
    /// `now` is a parameter rather than read from the clock so that the timeout is
    /// something a test can state instead of something it has to wait for.
    pub fn press(&mut self, mode: Mode, key: KeyEvent, now: Instant) -> Resolution {
        let chord = KeyChord::from_event(key);

        // The second half of a sequence, if the first half has not gone stale.
        if let Some(partial) = self.partial.take()
            && now.duration_since(partial.at) <= SEQUENCE_TIMEOUT
            && let Some(action) = self.map.action(mode, KeySeq::pair(partial.chord, chord))
        {
            return Resolution::Act(action);
        }

        // A complete binding wins over a prefix, so a key that does something does
        // it now rather than after a deadline.
        if let Some(action) = self.map.action(mode, KeySeq::single(chord)) {
            return Resolution::Act(action);
        }
        if self.map.is_prefix(mode, chord) {
            self.partial = Some(Partial { chord, at: now });
            return Resolution::Partial;
        }
        Resolution::Nothing
    }

    /// Drop a half-finished sequence that has run out of time.
    ///
    /// Called from the tick, so that the indicator on the message line goes away on
    /// its own. The timeout is enforced in [`Keys::press`] as well, and has to be:
    /// the next keypress may well arrive before the next tick.
    ///
    /// Returns whether anything was dropped, which is whether the screen changed.
    pub fn expire(&mut self, now: Instant) -> bool {
        let stale = self
            .partial
            .is_some_and(|partial| now.duration_since(partial.at) > SEQUENCE_TIMEOUT);
        if stale {
            self.partial = None;
        }
        stale
    }

    /// The half-finished sequence, for the corner of the message line.
    #[must_use]
    pub fn partial(&self) -> Option<String> {
        self.partial.map(|partial| partial.chord.to_string())
    }

    /// Forget any half-finished sequence, as leaving a mode does.
    pub fn clear(&mut self) {
        self.partial = None;
    }
}

// ---------------------------------------------------------------------------
// keys.toml
// ---------------------------------------------------------------------------

/// Something wrong with `keys.toml`, none of which stops the TUI starting.
///
/// Shaped like [`ConfigWarning`][mpdfm_core::config::ConfigWarning] and for the
/// same reason: a keymap file is a convenience, and refusing to start because one
/// line of it has a typo would take away the program the user was going to fix it
/// with. Every variant says what was ignored.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum KeyWarning {
    /// The file exists but could not be read.
    #[error("{path}: {message}; using the default keys")]
    Unreadable {
        /// The file.
        path: Utf8PathBuf,
        /// The operating system's explanation.
        message: String,
    },

    /// The file is not valid TOML, so none of it can be used.
    #[error("{path}: {message}; using the default keys")]
    MalformedToml {
        /// The file.
        path: Utf8PathBuf,
        /// The parser's explanation.
        message: String,
    },

    /// A section header that is not a mode.
    #[error("{path}: no mode called `[{section}]`; the modes are {}", modes())]
    UnknownMode {
        /// The file.
        path: Utf8PathBuf,
        /// The header as written.
        section: String,
    },

    /// A top-level entry that is not a section. Every binding lives under a mode.
    #[error("{path}: `{section}` is {found}, not a table of bindings; ignoring it")]
    NotASection {
        /// The file.
        path: Utf8PathBuf,
        /// The key as written.
        section: String,
        /// What was found instead, e.g. `a string`.
        found: &'static str,
    },

    /// A key specification that could not be read.
    #[error("{path}: [{mode}] \"{key}\": {source}; ignoring it")]
    BadKey {
        /// The file.
        path: Utf8PathBuf,
        /// The mode it was under.
        mode: Mode,
        /// The key as written.
        key: String,
        /// Why it could not be read.
        source: KeyError,
    },

    /// A binding whose value is not a string.
    #[error("{path}: [{mode}] \"{key}\" should be an action name, found {found}; ignoring it")]
    NotAnAction {
        /// The file.
        path: Utf8PathBuf,
        /// The mode it was under.
        mode: Mode,
        /// The key as written.
        key: String,
        /// What was found, e.g. `an integer`.
        found: &'static str,
    },

    /// An action name MPDFM does not have. A typo, or a later version's action.
    ///
    /// The message lists every valid name, because the one thing a user needs at
    /// that moment is the spelling they meant.
    #[error(
        "{path}: [{mode}] \"{key}\": no action called `{action}`; the actions are {}",
        listed(Action::names())
    )]
    UnknownAction {
        /// The file.
        path: Utf8PathBuf,
        /// The mode it was under.
        mode: Mode,
        /// The key as written.
        key: String,
        /// The action name as written.
        action: String,
    },

    /// A sequence that can never fire, because its first key is bound on its own.
    #[error(
        "{path}: [{mode}] \"{seq}\" can never fire: \"{first}\" is bound to `{shadow}` \
         and acts at once"
    )]
    Unreachable {
        /// The file.
        path: Utf8PathBuf,
        /// The mode.
        mode: Mode,
        /// The sequence that is now unreachable.
        seq: String,
        /// The chord that swallows it.
        first: String,
        /// What that chord does.
        shadow: Action,
    },
}

/// Every mode name, for the unknown-section warning.
fn modes() -> String {
    listed(Mode::ALL.iter().copied().map(Mode::name))
}

/// Names as `a, b, c`.
fn listed<'a>(names: impl Iterator<Item = &'a str>) -> String {
    names.collect::<Vec<_>>().join(", ")
}

/// The keymap to use: the defaults, with `path` merged over them.
///
/// An absent file is not a warning — most users will never write one, and MPDFM is
/// meant to work without it.
///
/// Never fails. Everything that can go wrong is a [`KeyWarning`] and leaves the
/// rest of the file in force, which is the task's requirement: one bad line must
/// not cost the user the other twenty.
#[must_use]
pub fn load(path: &Utf8Path) -> (KeyMap, Vec<KeyWarning>) {
    let mut warnings = Vec::new();
    let mut map = KeyMap::defaults();

    match std::fs::read_to_string(path) {
        Ok(text) => merge(&mut map, path, &text, &mut warnings),
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => {}
        Err(err) => warnings.push(KeyWarning::Unreadable {
            path: path.to_owned(),
            message: err.to_string(),
        }),
    }

    for (mode, seq, shadow) in map.unreachable() {
        warnings.push(KeyWarning::Unreachable {
            path: path.to_owned(),
            mode,
            seq: seq.to_string(),
            first: seq.first().to_string(),
            shadow,
        });
    }

    (map, warnings)
}

/// Apply `text` to `map`, collecting what could not be applied.
pub(crate) fn merge(map: &mut KeyMap, path: &Utf8Path, text: &str, warnings: &mut Vec<KeyWarning>) {
    let table: toml::Table = match text.parse() {
        Ok(table) => table,
        Err(err) => {
            warnings.push(KeyWarning::MalformedToml {
                path: path.to_owned(),
                message: err.message().to_owned(),
            });
            return;
        }
    };

    for (section, value) in table {
        let Some(bindings) = value.as_table() else {
            warnings.push(KeyWarning::NotASection {
                path: path.to_owned(),
                section,
                found: article(&value),
            });
            continue;
        };
        let Some(mode) = Mode::from_name(&section) else {
            warnings.push(KeyWarning::UnknownMode {
                path: path.to_owned(),
                section,
            });
            continue;
        };

        for (key, value) in bindings {
            let Some(name) = value.as_str() else {
                warnings.push(KeyWarning::NotAnAction {
                    path: path.to_owned(),
                    mode,
                    key: key.clone(),
                    found: article(value),
                });
                continue;
            };
            let seq = match KeySeq::parse(key) {
                Ok(seq) => seq,
                Err(source) => {
                    warnings.push(KeyWarning::BadKey {
                        path: path.to_owned(),
                        mode,
                        key: key.clone(),
                        source,
                    });
                    continue;
                }
            };
            if name == UNBIND {
                map.unbind(mode, seq);
                continue;
            }
            match Action::from_name(name) {
                Some(action) => map.bind(mode, seq, action),
                None => warnings.push(KeyWarning::UnknownAction {
                    path: path.to_owned(),
                    mode,
                    key: key.clone(),
                    action: name.to_owned(),
                }),
            }
        }
    }
}

/// What a TOML value is, as a warning would name it.
fn article(value: &toml::Value) -> &'static str {
    match value {
        toml::Value::String(_) => "a string",
        toml::Value::Integer(_) => "an integer",
        toml::Value::Float(_) => "a float",
        toml::Value::Boolean(_) => "a boolean",
        toml::Value::Datetime(_) => "a date",
        toml::Value::Array(_) => "an array",
        toml::Value::Table(_) => "a table",
    }
}

#[cfg(test)]
mod tests {
    use std::collections::HashSet;

    use super::*;

    /// A key event as the input thread delivers it.
    fn event(code: KeyCode, mods: KeyModifiers) -> KeyEvent {
        KeyEvent::new(code, mods)
    }

    /// A plain character press.
    fn ch(c: char) -> KeyEvent {
        event(KeyCode::Char(c), KeyModifiers::NONE)
    }

    /// Press a whole specification, chord by chord, and say what it resolved to.
    ///
    /// This is the path a real keypress takes — normalization, the sequence
    /// state machine, the table — rather than a direct lookup, which is what makes
    /// the table-driven test below an assertion about the app's behaviour.
    fn press_spec(keys: &mut Keys, mode: Mode, spec: &str) -> Resolution {
        let seq = KeySeq::parse(spec).expect("the test's own spelling parses");
        let now = Instant::now();
        let mut last = keys.press(mode, as_event(seq.first), now);
        if let Some(second) = seq.second {
            last = keys.press(mode, as_event(second), now);
        }
        last
    }

    /// A chord, back as the event that would produce it.
    fn as_event(chord: KeyChord) -> KeyEvent {
        event(chord.code, chord.mods)
    }

    // -- parsing -----------------------------------------------------------

    #[test]
    fn a_single_character_is_itself_and_a_name_is_a_named_key() {
        assert_eq!(KeyChord::parse("j").unwrap(), KeyChord::plain('j'));
        assert_eq!(KeyChord::parse("?").unwrap(), KeyChord::plain('?'));
        // The letter, not the function key: one character is always itself.
        assert_eq!(KeyChord::parse("f").unwrap(), KeyChord::plain('f'));
        assert_eq!(
            KeyChord::parse("f1").unwrap(),
            KeyChord::new(KeyCode::F(1), KeyModifiers::NONE)
        );
        assert_eq!(
            KeyChord::parse("enter").unwrap(),
            KeyChord::new(KeyCode::Enter, KeyModifiers::NONE)
        );
        assert_eq!(KeyChord::parse("space").unwrap(), KeyChord::plain(' '));
        assert_eq!(
            KeyChord::parse("ESC").unwrap(),
            KeyChord::new(KeyCode::Esc, KeyModifiers::NONE)
        );
    }

    #[test]
    fn minus_is_a_key_and_not_only_a_separator() {
        assert_eq!(KeyChord::parse("-").unwrap(), KeyChord::plain('-'));
        assert_eq!(
            KeyChord::parse("ctrl--").unwrap(),
            KeyChord::new(KeyCode::Char('-'), KeyModifiers::CONTROL)
        );
        // `-` is bound by default, and that is what it resolves to.
        let mut keys = Keys::new(KeyMap::defaults());
        assert_eq!(
            keys.press(Mode::Browser, ch('-'), Instant::now()),
            Resolution::Act(Action::Parent)
        );
    }

    #[test]
    fn a_modifier_has_to_be_spelled_out_so_that_a_dash_is_never_ambiguous() {
        assert_eq!(
            KeyChord::parse("ctrl-d").unwrap(),
            KeyChord::new(KeyCode::Char('d'), KeyModifiers::CONTROL)
        );
        assert_eq!(
            KeyChord::parse("alt-x").unwrap(),
            KeyChord::new(KeyCode::Char('x'), KeyModifiers::ALT)
        );
        // `a` is not an abbreviation for `alt`, so this is two keys and not one.
        assert!(KeyChord::parse("a-b").is_err());
        assert_eq!(
            KeySeq::parse("a b").unwrap(),
            KeySeq::pair(KeyChord::plain('a'), KeyChord::plain('b'))
        );
    }

    #[test]
    fn an_unknown_key_name_is_an_error_rather_than_a_guess() {
        assert_eq!(
            KeyChord::parse("wibble"),
            Err(KeyError::UnknownKey("wibble".to_owned()))
        );
        assert_eq!(KeyChord::parse(""), Err(KeyError::Empty));
        assert_eq!(KeySeq::parse("   "), Err(KeyError::Empty));
        assert_eq!(
            KeySeq::parse("g g g"),
            Err(KeyError::TooLong("g g g".to_owned()))
        );
    }

    #[test]
    fn a_sequence_is_written_together_or_apart_and_means_the_same_thing() {
        let gg = KeySeq::pair(KeyChord::plain('g'), KeyChord::plain('g'));
        assert_eq!(KeySeq::parse("gg").unwrap(), gg);
        assert_eq!(KeySeq::parse("g g").unwrap(), gg);
        // A modifier or a named key has to be written apart, because `ctrl-xs`
        // cannot be read any other way.
        assert_eq!(
            KeySeq::parse("ctrl-x s").unwrap(),
            KeySeq::pair(
                KeyChord::new(KeyCode::Char('x'), KeyModifiers::CONTROL),
                KeyChord::plain('s')
            )
        );
    }

    #[test]
    fn a_specification_survives_a_round_trip_through_display() {
        // The help overlay shows these strings and `keys.toml` takes them, so the
        // two notations have to be one notation.
        for spec in [
            "j",
            "G",
            "-",
            "space",
            "enter",
            "esc",
            "tab",
            "backspace",
            "ctrl-d",
            "alt-x",
            "f1",
            "up",
            "gg",
            "ctrl-x s",
        ] {
            let seq = KeySeq::parse(spec).expect(spec);
            assert_eq!(seq.to_string(), spec, "{spec} does not display as itself");
            assert_eq!(KeySeq::parse(&seq.to_string()).unwrap(), seq);
        }
    }

    // -- normalization -----------------------------------------------------

    #[test]
    fn shift_is_folded_into_the_character_so_every_terminal_agrees() {
        let upper = KeyChord::plain('J');
        assert_eq!(
            KeyChord::new(KeyCode::Char('j'), KeyModifiers::SHIFT),
            upper,
            "a terminal that reports shift must match a terminal that reports the capital"
        );
        assert_eq!(KeyChord::parse("shift-j").unwrap(), upper);
        assert_eq!(KeyChord::parse("J").unwrap(), upper);

        // The same thing is what makes `?` work everywhere, since shift is how it
        // is typed on most layouts.
        assert_eq!(
            KeyChord::new(KeyCode::Char('?'), KeyModifiers::SHIFT),
            KeyChord::plain('?')
        );
        let mut keys = Keys::new(KeyMap::defaults());
        assert_eq!(
            keys.press(
                Mode::Browser,
                event(KeyCode::Char('?'), KeyModifiers::SHIFT),
                Instant::now()
            ),
            Resolution::Act(Action::Help)
        );
    }

    #[test]
    fn shift_tab_is_backtab_and_modifiers_nobody_can_bind_are_dropped() {
        assert_eq!(
            KeyChord::new(KeyCode::Tab, KeyModifiers::SHIFT),
            KeyChord::new(KeyCode::BackTab, KeyModifiers::NONE)
        );
        assert_eq!(
            KeyChord::parse("shift-tab").unwrap().to_string(),
            "shift-tab"
        );

        // A terminal in the Kitty protocol reports extras on ordinary keys; they
        // must not stop a binding matching.
        let noisy = KeyModifiers::SUPER | KeyModifiers::HYPER;
        assert_eq!(
            KeyChord::new(KeyCode::Down, noisy),
            KeyChord::new(KeyCode::Down, KeyModifiers::NONE)
        );
    }

    #[test]
    fn ctrl_shift_is_one_chord_however_the_terminal_spells_it() {
        // The task's pitfall. Both spellings normalize to `ctrl-D`, so a user who
        // binds it gets it on either terminal — and the defaults still use none.
        let a = KeyChord::new(
            KeyCode::Char('d'),
            KeyModifiers::CONTROL | KeyModifiers::SHIFT,
        );
        let b = KeyChord::new(KeyCode::Char('D'), KeyModifiers::CONTROL);
        assert_eq!(a, b);
        assert_eq!(a.to_string(), "ctrl-D");
        assert_eq!(KeyChord::parse("ctrl-D").unwrap(), a);
        assert_ne!(a, KeyChord::parse("ctrl-d").unwrap());
    }

    // -- the defaults ------------------------------------------------------

    /// Every default binding from `docs/tasks/21-keymap.md`, pressed for real.
    #[test]
    fn every_default_binding_dispatches_its_action() {
        #[rustfmt::skip]
        let table: &[(&str, Action)] = &[
            ("h", Action::Left), ("left", Action::Left),
            ("j", Action::Down), ("down", Action::Down),
            ("k", Action::Up), ("up", Action::Up),
            ("l", Action::Right), ("right", Action::Right),
            ("gg", Action::Top), ("G", Action::Bottom),
            ("enter", Action::Open),
            ("-", Action::Parent), ("backspace", Action::Parent),
            ("tab", Action::SwitchPane),
            ("ctrl-d", Action::HalfPageDown), ("ctrl-u", Action::HalfPageUp),
            ("space", Action::ToggleMark),
            ("v", Action::VisualSelect),
            ("a", Action::MarkAll), ("A", Action::UnmarkAll),
            ("e", Action::EditTags),
            ("m", Action::StageMove),
            ("r", Action::Rename),
            ("d", Action::StageDelete),
            ("o", Action::Organize),
            ("p", Action::ShowPending),
            ("c", Action::Commit),
            ("x", Action::DiscardPending),
            ("u", Action::Undo),
            ("/", Action::Search),
            ("n", Action::SearchNext), ("N", Action::SearchPrev),
            ("f", Action::Filter),
            ("F", Action::FindLibrary),
            ("esc", Action::Cancel),
            (":", Action::CommandMode),
            ("?", Action::Help),
            ("R", Action::Rescan),
            ("q", Action::Quit),
        ];

        let mut keys = Keys::new(KeyMap::defaults());
        for (spec, expected) in table {
            assert_eq!(
                press_spec(&mut keys, Mode::Browser, spec),
                Resolution::Act(*expected),
                "`{spec}` should be `{expected}`"
            );
            keys.clear();
        }

        // And the table above is the whole of the browser's keymap, so a binding
        // cannot be added to the defaults without being covered here.
        let bound: HashSet<String> = KeyMap::defaults()
            .bindings(Mode::Browser)
            .into_iter()
            .map(|(seq, _)| seq.to_string())
            .collect();
        let tested: HashSet<String> = table.iter().map(|(spec, _)| (*spec).to_owned()).collect();
        assert_eq!(
            bound.difference(&tested).collect::<Vec<_>>(),
            Vec::<&String>::new(),
            "a default binding is not in the table-driven test"
        );
    }

    #[test]
    fn the_default_spellings_all_parse() {
        // `KeyMap::defaults` panics on a bad spelling; this is the test that says
        // so before a user meets it.
        let map = KeyMap::defaults();
        for &mode in Mode::ALL {
            assert!(
                !map.bindings(mode).is_empty(),
                "[{mode}] has no default bindings"
            );
        }
        assert!(
            map.unreachable().is_empty(),
            "the defaults shadow one of their own sequences: {:?}",
            map.unreachable()
        );
    }

    #[test]
    fn the_same_key_means_different_things_in_different_modes() {
        let map = KeyMap::defaults();
        let ctrl_u = KeySeq::single(KeyChord::parse("ctrl-u").unwrap());
        assert_eq!(map.action(Mode::Browser, ctrl_u), Some(Action::HalfPageUp));
        assert_eq!(map.action(Mode::Command, ctrl_u), Some(Action::ClearLine));

        // And a letter that commands in the browser is free to be typed in a mode
        // that takes text.
        let d = KeySeq::single(KeyChord::plain('d'));
        assert_eq!(map.action(Mode::Browser, d), Some(Action::StageDelete));
        assert_eq!(map.action(Mode::Command, d), None);
        // In the pending view it is the first half of `dd`, which is what takes
        // an operation off the plan: one `d` there is a sequence waiting for its
        // second key and not a delete (`docs/tasks/24-pending-view.md`).
        assert_eq!(map.action(Mode::Pending, d), None);
        assert!(map.is_prefix(Mode::Pending, KeyChord::plain('d')));
        assert_eq!(
            map.action(Mode::Pending, KeySeq::parse("dd").expect("a sequence")),
            Some(Action::Unstage)
        );
    }

    #[test]
    fn force_quit_is_reachable_by_name_even_though_nothing_is_bound_to_it() {
        // `:q!` and the confirmation prompt are how a user reaches it; a
        // `keys.toml` can bind it like anything else.
        let map = KeyMap::defaults();
        assert!(
            !map.bindings(Mode::Browser)
                .iter()
                .any(|(_, action)| *action == Action::ForceQuit)
        );
        assert_eq!(Action::from_name("force_quit"), Some(Action::ForceQuit));
    }

    // -- sequences ---------------------------------------------------------

    #[test]
    fn gg_works_as_a_sequence_and_a_lone_g_times_out_into_nothing() {
        let mut keys = Keys::new(KeyMap::defaults());
        let start = Instant::now();

        // `g` on its own is bound to nothing, so it waits.
        assert_eq!(
            keys.press(Mode::Browser, ch('g'), start),
            Resolution::Partial
        );
        assert_eq!(keys.partial().as_deref(), Some("g"));
        assert_eq!(
            keys.press(Mode::Browser, ch('g'), start + Duration::from_millis(80)),
            Resolution::Act(Action::Top)
        );
        assert_eq!(keys.partial(), None, "a finished sequence is not pending");

        // A lone `g` followed by the timeout: the tick drops it, and nothing
        // happened.
        assert_eq!(
            keys.press(Mode::Browser, ch('g'), start),
            Resolution::Partial
        );
        assert!(!keys.expire(start + Duration::from_millis(10)), "not yet");
        assert_eq!(keys.partial().as_deref(), Some("g"));
        assert!(keys.expire(start + SEQUENCE_TIMEOUT + Duration::from_millis(1)));
        assert_eq!(keys.partial(), None);

        // And the timeout holds against the next keypress too, which may well
        // arrive before the next tick: a late `g` starts over rather than
        // completing the sequence.
        assert_eq!(
            keys.press(Mode::Browser, ch('g'), start),
            Resolution::Partial
        );
        assert_eq!(
            keys.press(
                Mode::Browser,
                ch('g'),
                start + SEQUENCE_TIMEOUT + Duration::from_millis(1)
            ),
            Resolution::Partial,
            "a stale first half must not complete a sequence"
        );
    }

    #[test]
    fn a_prefix_followed_by_something_else_falls_back_to_that_key_alone() {
        let mut keys = Keys::new(KeyMap::defaults());
        let now = Instant::now();
        assert_eq!(keys.press(Mode::Browser, ch('g'), now), Resolution::Partial);
        // `gj` is not bound, so the `j` is a `j`.
        assert_eq!(
            keys.press(Mode::Browser, ch('j'), now),
            Resolution::Act(Action::Down),
            "an abandoned prefix must not swallow the key that abandoned it"
        );
        assert_eq!(keys.partial(), None);
    }

    #[test]
    fn an_unbound_key_resolves_to_nothing_so_a_view_can_take_it_as_text() {
        let mut keys = Keys::new(KeyMap::defaults());
        assert_eq!(
            keys.press(Mode::Browser, ch('Z'), Instant::now()),
            Resolution::Nothing
        );
        // Which is exactly what command mode relies on for every letter it types.
        assert_eq!(
            keys.press(Mode::Command, ch('m'), Instant::now()),
            Resolution::Nothing
        );
        assert_eq!(KeyChord::plain('m').typed(), Some('m'));
        assert_eq!(
            KeyChord::new(KeyCode::Char('m'), KeyModifiers::CONTROL).typed(),
            None,
            "a modifier means a command nobody claimed, not a letter"
        );
    }

    // -- keys.toml ---------------------------------------------------------

    /// Merge a `keys.toml` body over the defaults.
    fn merged(text: &str) -> (KeyMap, Vec<KeyWarning>) {
        let mut map = KeyMap::defaults();
        let mut warnings = Vec::new();
        merge(&mut map, Utf8Path::new("keys.toml"), text, &mut warnings);
        (map, warnings)
    }

    #[test]
    fn keys_toml_overrides_a_default_and_adds_a_new_binding() {
        // The task's own example.
        let (map, warnings) = merged(
            r#"
            [browser]
            "ctrl-r" = "rescan"
            "J" = "half_page_down"
            "#,
        );
        assert!(warnings.is_empty(), "{warnings:?}");

        let ctrl_r = KeySeq::parse("ctrl-r").unwrap();
        assert_eq!(map.action(Mode::Browser, ctrl_r), Some(Action::Rescan));
        // The new binding is in addition: `R` still rescans, because nothing said
        // otherwise.
        let r = KeySeq::parse("R").unwrap();
        assert_eq!(map.action(Mode::Browser, r), Some(Action::Rescan));
        // And `J`, which was not bound at all, now is.
        let j = KeySeq::parse("J").unwrap();
        assert_eq!(map.action(Mode::Browser, j), Some(Action::HalfPageDown));
    }

    #[test]
    fn rebinding_a_key_does_not_leave_the_old_binding_active() {
        let (map, warnings) = merged(
            r#"
            [browser]
            "d" = "stage_move"
            "R" = "none"
            "#,
        );
        assert!(warnings.is_empty(), "{warnings:?}");

        // One action per key: `d` is a move now, and nothing is left of the
        // delete it used to stage.
        let d = KeySeq::parse("d").unwrap();
        assert_eq!(map.action(Mode::Browser, d), Some(Action::StageMove));
        assert!(
            !map.bindings(Mode::Browser)
                .iter()
                .any(|(seq, action)| *action == Action::StageDelete && *seq == d)
        );

        // And `= "none"` takes a key away rather than pointing it somewhere else,
        // which is the only way to free one up.
        assert_eq!(map.action(Mode::Browser, KeySeq::parse("R").unwrap()), None);

        let mut keys = Keys::new(map);
        assert_eq!(
            keys.press(Mode::Browser, ch('d'), Instant::now()),
            Resolution::Act(Action::StageMove)
        );
        assert_eq!(
            keys.press(Mode::Browser, ch('R'), Instant::now()),
            Resolution::Nothing
        );
    }

    #[test]
    fn an_unknown_action_warns_and_the_rest_of_the_file_still_applies() {
        let (map, warnings) = merged(
            r#"
            [browser]
            "ctrl-r" = "rescann"
            "Y" = "commit"

            [pending]
            "ctrl-y" = "undo"
            "#,
        );

        assert_eq!(warnings.len(), 1, "{warnings:?}");
        let message = warnings[0].to_string();
        assert!(message.contains("rescann"), "{message}");
        // "listing valid actions": the spelling the user meant is in the message.
        assert!(message.contains("rescan"), "{message}");
        assert!(message.contains("half_page_down"), "{message}");

        // The bad line is the only casualty.
        assert_eq!(
            map.action(Mode::Browser, KeySeq::parse("ctrl-r").unwrap()),
            None
        );
        assert_eq!(
            map.action(Mode::Browser, KeySeq::parse("Y").unwrap()),
            Some(Action::Commit)
        );
        assert_eq!(
            map.action(Mode::Pending, KeySeq::parse("ctrl-y").unwrap()),
            Some(Action::Undo)
        );
    }

    #[test]
    fn every_other_kind_of_bad_line_warns_and_is_skipped() {
        let (map, warnings) = merged(
            r#"
            whatever = "not a section"

            [wibble]
            "x" = "quit"

            [browser]
            "wibble" = "quit"
            "g g g" = "quit"
            "Y" = 7
            "Z" = "commit"
            "#,
        );

        let messages: Vec<String> = warnings.iter().map(ToString::to_string).collect();
        let joined = messages.join("\n");
        assert_eq!(warnings.len(), 5, "{joined}");
        assert!(joined.contains("not a table of bindings"), "{joined}");
        assert!(joined.contains("no mode called `[wibble]`"), "{joined}");
        assert!(joined.contains("no key called `wibble`"), "{joined}");
        assert!(joined.contains("more than two keys"), "{joined}");
        assert!(joined.contains("found an integer"), "{joined}");
        // The unknown-mode warning names the modes that do exist.
        assert!(joined.contains("browser, pending, tagedit"), "{joined}");

        // The one good line applied.
        assert_eq!(
            map.action(Mode::Browser, KeySeq::parse("Z").unwrap()),
            Some(Action::Commit)
        );
    }

    #[test]
    fn malformed_toml_warns_once_and_leaves_the_defaults_alone() {
        let (map, warnings) = merged("[browser\n\"x\" = \"quit\"\n");
        assert_eq!(warnings.len(), 1, "{warnings:?}");
        assert!(
            warnings[0].to_string().contains("using the default keys"),
            "{}",
            warnings[0]
        );
        assert_eq!(map, KeyMap::defaults());
    }

    #[test]
    fn a_binding_that_swallows_a_sequence_is_reported_rather_than_left_to_surprise() {
        let dir = tempfile::tempdir().expect("temp dir");
        let path = Utf8PathBuf::from_path_buf(dir.path().join("keys.toml")).expect("utf-8");
        std::fs::write(&path, "[browser]\n\"g\" = \"top\"\n").expect("write");

        let (map, warnings) = load(&path);
        // `g` acts at once, which is what the user asked for.
        assert_eq!(
            map.action(Mode::Browser, KeySeq::parse("g").unwrap()),
            Some(Action::Top)
        );
        let mut keys = Keys::new(map);
        assert_eq!(
            keys.press(Mode::Browser, ch('g'), Instant::now()),
            Resolution::Act(Action::Top),
            "a complete binding must not wait for a deadline"
        );

        // And `gg` is now unreachable, which is said out loud.
        let message = warnings
            .iter()
            .map(ToString::to_string)
            .find(|text| text.contains("can never fire"))
            .unwrap_or_else(|| panic!("{warnings:?}"));
        assert!(message.contains("\"gg\""), "{message}");
        assert!(message.contains("`top`"), "{message}");
    }

    #[test]
    fn an_absent_keys_file_is_the_defaults_and_not_a_warning() {
        let dir = tempfile::tempdir().expect("temp dir");
        let path = Utf8PathBuf::from_path_buf(dir.path().join("nothing-here.toml")).expect("utf-8");
        let (map, warnings) = load(&path);
        assert_eq!(map, KeyMap::defaults());
        assert!(warnings.is_empty(), "{warnings:?}");
    }

    #[test]
    fn a_keys_file_that_cannot_be_read_warns_and_the_defaults_stand() {
        let dir = tempfile::tempdir().expect("temp dir");
        // A directory where a file should be: open(2) fails with EISDIR, which is
        // the readable-looking-but-unreadable case.
        let path = Utf8PathBuf::from_path_buf(dir.path().join("keys.toml")).expect("utf-8");
        std::fs::create_dir(&path).expect("mkdir");

        let (map, warnings) = load(&path);
        assert_eq!(map, KeyMap::defaults());
        assert_eq!(warnings.len(), 1, "{warnings:?}");
        assert!(
            warnings[0].to_string().contains("using the default keys"),
            "{}",
            warnings[0]
        );
    }

    #[test]
    fn the_shipped_example_file_applies_cleanly_once_uncommented() {
        // Every binding in `docs/keys.example.toml` is commented out, so the file
        // as shipped changes nothing; uncommenting all of it has to still parse,
        // or the documentation is wrong about its own syntax.
        let example = include_str!("../../docs/keys.example.toml");
        let (_, warnings) = merged(example);
        assert!(warnings.is_empty(), "the file as shipped: {warnings:?}");

        // The sections and the bindings, which are the lines that start in column
        // one once the `# ` comes off. The prose is indented and stays commented.
        let uncommented: String = example
            .lines()
            .filter_map(|line| line.strip_prefix("# "))
            .filter(|line| line.starts_with('[') || line.starts_with('"'))
            .fold(String::new(), |mut text, line| {
                let _ = writeln!(text, "{line}");
                text
            });
        assert!(
            uncommented.contains("[browser]") && uncommented.contains("[command]"),
            "the test found no bindings to uncomment:\n{uncommented}"
        );
        let (_, warnings) = merged(&uncommented);
        assert!(warnings.is_empty(), "uncommented: {warnings:?}");
    }

    #[test]
    fn the_example_file_lists_every_action_there_is() {
        // The file ends with the whole vocabulary, because an unknown action's
        // warning tells the user to go and look at it. A list that has drifted from
        // the code is worse than no list, so it is not allowed to drift.
        let example = include_str!("../../docs/keys.example.toml");
        for name in Action::names() {
            assert!(
                example.contains(name),
                "`{name}` is an action and docs/keys.example.toml does not mention it"
            );
        }
        // And the sentinel, which is not an action and has to be documented anyway.
        assert!(example.contains(UNBIND), "`{UNBIND}` is undocumented");
    }

    // -- help --------------------------------------------------------------

    #[test]
    fn the_help_is_generated_from_the_table_and_a_remap_changes_it() {
        let help = KeyMap::defaults().help();
        let browser = help
            .iter()
            .find(|section| section.mode == Mode::Browser)
            .expect("there is a browser section");

        // Keys bound to the same action share a row, shortest first.
        let down = browser
            .rows
            .iter()
            .find(|row| row.action == Action::Down)
            .expect("down is bound");
        assert_eq!(down.keys, "j / down");
        assert_eq!(down.action.help(), "move down");

        // Nothing is listed that is not bound, which is the property that makes a
        // generated help page worth generating.
        assert!(
            !browser
                .rows
                .iter()
                .any(|row| row.action == Action::ForceQuit),
            "force_quit has no default key and must not be documented"
        );

        // And a remap moves with the table.
        let (remapped, _) = merged("[browser]\n\"j\" = \"none\"\n\"J\" = \"down\"\n");
        let down = remapped
            .help()
            .into_iter()
            .find(|section| section.mode == Mode::Browser)
            .expect("browser")
            .rows
            .into_iter()
            .find(|row| row.action == Action::Down)
            .expect("down is still bound");
        assert_eq!(down.keys, "J / down");
    }

    #[test]
    fn every_mode_has_a_help_section_even_the_ones_no_view_reaches_yet() {
        let help = KeyMap::defaults().help();
        assert_eq!(help.len(), Mode::ALL.len());
        for section in help {
            assert!(!section.rows.is_empty(), "[{}] has no rows", section.mode);
        }
    }
}
